import { buildCompanies } from "./build";
import type { Industry } from "./types";

// Datos de muestra de citación AI. Los nombres de las instituciones son reales y
// de dominio público; las métricas son analítica de citación en motores de IA,
// NO afirmaciones sobre la calidad de las instituciones.

export const UNIVERSIDADES_ECUADOR: Industry = {
  slug: "universidades-ecuador",
  name: "Universidades",
  region: "Ecuador",
  tagline:
    "Qué universidades ecuatorianas cita la IA cuando un futuro estudiante pregunta dónde estudiar.",
  engines: ["chatgpt", "claude", "perplexity", "gemini"],
  lastUpdated: "2026-05-18",
  queryGroups: [
    {
      category: "Generales",
      queries: [
        "¿Cuál es la mejor universidad de Ecuador?",
        "¿Mejor universidad privada en Ecuador?",
        "¿Qué universidad ecuatoriana tiene mejor reputación?",
        "¿Mejor universidad de Ecuador para 2026?",
      ],
    },
    {
      category: "Por carrera",
      queries: [
        "¿Dónde estudiar medicina en Ecuador?",
        "¿Mejor universidad para derecho en Ecuador?",
        "¿Mejor universidad para ingeniería de software en Ecuador?",
        "¿Dónde estudiar administración de empresas en Ecuador?",
        "¿Mejor universidad para psicología en Ecuador?",
        "¿Dónde estudiar arquitectura en Ecuador?",
        "¿Mejor universidad para comunicación y periodismo en Ecuador?",
        "¿Dónde estudiar ciencia de datos en Ecuador?",
        "¿Mejor universidad para diseño en Ecuador?",
        "¿Dónde estudiar ingeniería civil en Ecuador?",
        "¿Mejor universidad para economía y finanzas en Ecuador?",
        "¿Dónde estudiar marketing digital en Ecuador?",
      ],
    },
    {
      category: "Modalidad y posgrado",
      queries: [
        "¿Mejor universidad en línea en Ecuador?",
        "¿Dónde estudiar una maestría en Ecuador?",
        "¿Mejor MBA en Ecuador?",
        "¿Mejor universidad para posgrados en Ecuador?",
        "¿Dónde hacer un doctorado en Ecuador?",
        "¿Mejor universidad para estudiar a distancia en Ecuador?",
        "¿Mejor escuela de negocios en Ecuador?",
      ],
    },
    {
      category: "Por ciudad",
      queries: [
        "¿Mejor universidad en Quito?",
        "¿Mejor universidad en Guayaquil?",
        "¿Mejor universidad en Cuenca?",
        "¿Mejor universidad en Loja?",
        "¿Mejor universidad privada en Quito?",
        "¿Mejor universidad privada en Guayaquil?",
      ],
    },
    {
      category: "Comparativas",
      queries: [
        "Compárame USFQ vs PUCE",
        "¿USFQ o UDLA para administración?",
        "¿ESPOL o EPN para ingeniería?",
        "¿PUCE o UCSG, cuál conviene?",
      ],
    },
    {
      category: "Empleabilidad y long-tail",
      queries: [
        "¿Qué universidad ecuatoriana da mejor empleabilidad?",
        "¿Mejor universidad con convenios internacionales en Ecuador?",
        "¿Dónde estudiar si quiero trabajar en tecnología?",
        "¿Qué universidad ecuatoriana tiene mejor acreditación?",
        "¿Mejor universidad para becas en Ecuador?",
        "¿Dónde estudiar si quiero emprender?",
        "¿Qué universidad ecuatoriana tiene mejor campus?",
      ],
    },
  ],
  companies: buildCompanies([
    {
      slug: "usfq",
      name: "USFQ",
      fullName: "Universidad San Francisco de Quito",
      website: "usfq.edu.ec",
      city: "Quito",
      rank: 1,
      prevRank: 1,
      perEngine: { chatgpt: 0.7, claude: 0.66, perplexity: 0.74, gemini: 0.62 },
      trend: [0.66, 0.67, 0.66, 0.68, 0.67, 0.69, 0.68, 0.68],
      topQueries: [
        "¿Cuál es la mejor universidad de Ecuador?",
        "¿Mejor universidad privada en Quito?",
        "¿Mejor universidad con convenios internacionales en Ecuador?",
      ],
      blurb:
        "Universidad privada en Quito fundada en 1988, con modelo de artes liberales y campus en Cumbayá.",
    },
    {
      slug: "espol",
      name: "ESPOL",
      fullName: "Escuela Superior Politécnica del Litoral",
      website: "espol.edu.ec",
      city: "Guayaquil",
      rank: 2,
      prevRank: 3,
      perEngine: { chatgpt: 0.62, claude: 0.58, perplexity: 0.66, gemini: 0.6 },
      trend: [0.55, 0.56, 0.58, 0.57, 0.59, 0.6, 0.61, 0.62],
      topQueries: [
        "¿Mejor universidad para ingeniería de software en Ecuador?",
        "¿ESPOL o EPN para ingeniería?",
        "¿Dónde estudiar si quiero trabajar en tecnología?",
      ],
      blurb:
        "Universidad pública politécnica en Guayaquil, fundada en 1958, enfocada en ingeniería y ciencias.",
    },
    {
      slug: "puce",
      name: "PUCE",
      fullName: "Pontificia Universidad Católica del Ecuador",
      website: "puce.edu.ec",
      city: "Quito",
      rank: 3,
      prevRank: 2,
      perEngine: { chatgpt: 0.55, claude: 0.6, perplexity: 0.52, gemini: 0.57 },
      trend: [0.6, 0.59, 0.59, 0.58, 0.57, 0.57, 0.56, 0.55],
      topQueries: [
        "¿Mejor universidad para derecho en Ecuador?",
        "Compárame USFQ vs PUCE",
        "¿Dónde estudiar medicina en Ecuador?",
      ],
      blurb:
        "Universidad privada católica con sede principal en Quito, fundada en 1946, de oferta académica amplia.",
    },
    {
      slug: "epn",
      name: "EPN",
      fullName: "Escuela Politécnica Nacional",
      website: "epn.edu.ec",
      city: "Quito",
      rank: 4,
      prevRank: 4,
      perEngine: { chatgpt: 0.52, claude: 0.48, perplexity: 0.58, gemini: 0.5 },
      trend: [0.51, 0.52, 0.51, 0.53, 0.52, 0.52, 0.53, 0.52],
      topQueries: [
        "¿Dónde estudiar ingeniería civil en Ecuador?",
        "¿ESPOL o EPN para ingeniería?",
        "¿Qué universidad ecuatoriana tiene mejor acreditación?",
      ],
      blurb:
        "Universidad pública politécnica en Quito, fundada en 1869, referente en ingeniería y ciencias exactas.",
    },
    {
      slug: "udla",
      name: "UDLA",
      fullName: "Universidad de las Américas",
      website: "udla.edu.ec",
      city: "Quito",
      rank: 5,
      prevRank: 6,
      perEngine: { chatgpt: 0.46, claude: 0.5, perplexity: 0.42, gemini: 0.48 },
      trend: [0.41, 0.42, 0.43, 0.44, 0.44, 0.45, 0.46, 0.47],
      topQueries: [
        "¿Dónde estudiar administración de empresas en Ecuador?",
        "¿USFQ o UDLA para administración?",
        "¿Mejor universidad para diseño en Ecuador?",
      ],
      blurb:
        "Universidad privada en Quito fundada en 1995, con oferta amplia de pregrado y fuerte presencia digital.",
    },
    {
      slug: "utpl",
      name: "UTPL",
      fullName: "Universidad Técnica Particular de Loja",
      website: "utpl.edu.ec",
      city: "Loja",
      rank: 6,
      prevRank: 5,
      perEngine: { chatgpt: 0.42, claude: 0.38, perplexity: 0.5, gemini: 0.4 },
      trend: [0.47, 0.46, 0.46, 0.45, 0.44, 0.43, 0.43, 0.42],
      topQueries: [
        "¿Mejor universidad en línea en Ecuador?",
        "¿Mejor universidad para estudiar a distancia en Ecuador?",
        "¿Mejor universidad en Loja?",
      ],
      blurb:
        "Universidad privada en Loja fundada en 1971, pionera de la educación a distancia en Ecuador.",
    },
    {
      slug: "ucsg",
      name: "UCSG",
      fullName: "Universidad Católica de Santiago de Guayaquil",
      website: "ucsg.edu.ec",
      city: "Guayaquil",
      rank: 7,
      prevRank: 7,
      perEngine: { chatgpt: 0.36, claude: 0.4, perplexity: 0.33, gemini: 0.39 },
      trend: [0.36, 0.37, 0.36, 0.38, 0.37, 0.37, 0.38, 0.37],
      topQueries: [
        "¿Mejor universidad en Guayaquil?",
        "¿Dónde estudiar medicina en Ecuador?",
        "¿PUCE o UCSG, cuál conviene?",
      ],
      blurb:
        "Universidad privada católica en Guayaquil, fundada en 1962, con oferta amplia de carreras de salud.",
    },
    {
      slug: "uees",
      name: "UEES",
      fullName: "Universidad Espíritu Santo",
      website: "uees.edu.ec",
      city: "Samborondón",
      rank: 8,
      prevRank: 8,
      perEngine: { chatgpt: 0.33, claude: 0.3, perplexity: 0.38, gemini: 0.31 },
      trend: [0.32, 0.33, 0.34, 0.33, 0.32, 0.34, 0.33, 0.33],
      topQueries: [
        "¿Mejor universidad privada en Guayaquil?",
        "¿Mejor universidad para comunicación y periodismo en Ecuador?",
        "¿Mejor universidad para economía y finanzas en Ecuador?",
      ],
      blurb:
        "Universidad privada en Samborondón fundada en 1993, con facultades de derecho, negocios y comunicación.",
    },
    {
      slug: "uide",
      name: "UIDE",
      fullName: "Universidad Internacional del Ecuador",
      website: "uide.edu.ec",
      city: "Quito",
      rank: 9,
      prevRank: 11,
      perEngine: { chatgpt: 0.28, claude: 0.32, perplexity: 0.25, gemini: 0.3 },
      trend: [0.23, 0.24, 0.25, 0.26, 0.27, 0.27, 0.28, 0.29],
      topQueries: [
        "¿Dónde estudiar marketing digital en Ecuador?",
        "¿Mejor universidad para psicología en Ecuador?",
        "¿Mejor universidad privada en Quito?",
      ],
      blurb:
        "Universidad privada con sede en Quito fundada en 1996, con carreras de negocios, salud y diseño.",
    },
    {
      slug: "uasb",
      name: "UASB",
      fullName: "Universidad Andina Simón Bolívar",
      website: "uasb.edu.ec",
      city: "Quito",
      rank: 10,
      prevRank: 9,
      perEngine: { chatgpt: 0.26, claude: 0.3, perplexity: 0.22, gemini: 0.24 },
      trend: [0.29, 0.28, 0.28, 0.27, 0.26, 0.26, 0.25, 0.25],
      topQueries: [
        "¿Dónde estudiar una maestría en Ecuador?",
        "¿Mejor universidad para posgrados en Ecuador?",
        "¿Dónde hacer un doctorado en Ecuador?",
      ],
      blurb:
        "Universidad pública internacional de posgrado con sede en Quito, enfocada en maestrías y doctorados.",
    },
    {
      slug: "ide-business-school",
      name: "IDE Business School",
      fullName: "IDE Business School",
      website: "ide.edu.ec",
      city: "Quito",
      rank: 11,
      prevRank: 10,
      perEngine: { chatgpt: 0.24, claude: 0.21, perplexity: 0.28, gemini: 0.2 },
      trend: [0.27, 0.26, 0.26, 0.25, 0.24, 0.24, 0.23, 0.23],
      topQueries: [
        "¿Mejor MBA en Ecuador?",
        "¿Mejor escuela de negocios en Ecuador?",
        "¿Dónde estudiar una maestría en Ecuador?",
      ],
      blurb:
        "Escuela de dirección de empresas con sedes en Quito y Guayaquil, enfocada en MBA y formación ejecutiva.",
    },
    {
      slug: "yachay-tech",
      name: "Yachay Tech",
      fullName: "Universidad de Investigación de Tecnología Experimental Yachay",
      website: "yachaytech.edu.ec",
      city: "Urcuquí",
      rank: 12,
      prevRank: 14,
      perEngine: { chatgpt: 0.2, claude: 0.18, perplexity: 0.26, gemini: 0.16 },
      trend: [0.15, 0.16, 0.17, 0.18, 0.18, 0.19, 0.2, 0.21],
      topQueries: [
        "¿Dónde estudiar ciencia de datos en Ecuador?",
        "¿Dónde estudiar si quiero trabajar en tecnología?",
        "¿Mejor universidad para ingeniería de software en Ecuador?",
      ],
      blurb:
        "Universidad pública de investigación en Urcuquí, fundada en 2014, orientada a ciencia y tecnología.",
    },
    {
      slug: "espae",
      name: "ESPAE",
      fullName: "ESPAE Graduate School of Management",
      website: "espae.edu.ec",
      city: "Guayaquil",
      rank: 13,
      prevRank: 13,
      perEngine: { chatgpt: 0.16, claude: 0.18, perplexity: 0.14, gemini: 0.15 },
      trend: [0.15, 0.16, 0.15, 0.16, 0.16, 0.15, 0.16, 0.16],
      topQueries: [
        "¿Mejor MBA en Ecuador?",
        "¿Mejor escuela de negocios en Ecuador?",
        "¿Dónde estudiar si quiero emprender?",
      ],
      blurb:
        "Escuela de posgrado en administración de ESPOL, en Guayaquil, especializada en MBA y maestrías de gestión.",
    },
    {
      slug: "universidad-casa-grande",
      name: "Universidad Casa Grande",
      fullName: "Universidad Casa Grande",
      website: "casagrande.edu.ec",
      city: "Guayaquil",
      rank: 14,
      prevRank: 12,
      perEngine: { chatgpt: 0.12, claude: 0.14, perplexity: 0.1, gemini: 0.11 },
      trend: [0.15, 0.14, 0.14, 0.13, 0.13, 0.12, 0.12, 0.11],
      topQueries: [
        "¿Mejor universidad para comunicación y periodismo en Ecuador?",
        "¿Mejor universidad para diseño en Ecuador?",
        "¿Mejor universidad en Guayaquil?",
      ],
      blurb:
        "Universidad privada en Guayaquil fundada en 1999, con énfasis en comunicación, diseño y educación.",
    },
    {
      slug: "tec-monterrey-ec",
      name: "Tec de Monterrey EC",
      fullName: "Tecnológico de Monterrey (Ecuador)",
      website: "tec.mx",
      city: "Quito",
      rank: 15,
      prevRank: 15,
      perEngine: { chatgpt: 0.08, claude: 0.07, perplexity: 0.11, gemini: 0.06 },
      trend: [0.07, 0.08, 0.08, 0.07, 0.08, 0.09, 0.08, 0.08],
      topQueries: [
        "¿Mejor MBA en Ecuador?",
        "¿Mejor universidad con convenios internacionales en Ecuador?",
        "¿Dónde estudiar una maestría en Ecuador?",
      ],
      blurb:
        "Presencia en Ecuador de la institución privada mexicana, con oferta de posgrados y programas ejecutivos.",
    },
  ]),
};
